### ISSUE TITLE
New Arguments

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Foster-Manager#1]
**TODOs**:
 - [x] Add Foster information conversion.
 - [x] Add encryption conversion support.
 - [x] Add compression algorithm conversion support.
 - [x] Add empty Foster information file creation support.
