### ISSUE TITLE
Sync, Query and Remove features

### ISSUE THREAD

**Issue by ivanthesexy** [Haltroy/Foster-Manager#3]
With [Foster issue #12](https://github.com/Haltroy/Foster/issues/12), Foster Manager can update (sync), query or remove a deleted package that is either installed by Foster Manager or another project.

**TODO**:
- [ ] Add `sync` function.
- [ ] Add `query-installed` function.
- [ ] Add `remove` function.

**Comment by Haltroy** [comment]
Options of both #3 and #4 are added as `Not Implemented` so for now, they will throw `NotImplementedException()` on start.
